// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1vjPlsp3I-GX3xAJ6FMzTcjilqjHYMPo',
    appId: '1:533072993224:web:8f04c1df38c058aacc7efd',
    messagingSenderId: '533072993224',
    projectId: 'cpmd-final',
    authDomain: 'cpmd-final.firebaseapp.com',
    storageBucket: 'cpmd-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2pqgq1SntymiCywamQdK9zn8YyhwniwA',
    appId: '1:533072993224:android:31b70cbd76fff705cc7efd',
    messagingSenderId: '533072993224',
    projectId: 'cpmd-final',
    storageBucket: 'cpmd-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAgmMeR5yKwqeHlhXayKw0zox6FdL859Y',
    appId: '1:533072993224:ios:7383ebdeefc7eb8ecc7efd',
    messagingSenderId: '533072993224',
    projectId: 'cpmd-final',
    storageBucket: 'cpmd-final.firebasestorage.app',
    iosBundleId: 'com.sweezy.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAgmMeR5yKwqeHlhXayKw0zox6FdL859Y',
    appId: '1:533072993224:ios:1865ca88bf1eb1fecc7efd',
    messagingSenderId: '533072993224',
    projectId: 'cpmd-final',
    storageBucket: 'cpmd-final.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1vjPlsp3I-GX3xAJ6FMzTcjilqjHYMPo',
    appId: '1:533072993224:web:385918a89461756fcc7efd',
    messagingSenderId: '533072993224',
    projectId: 'cpmd-final',
    authDomain: 'cpmd-final.firebaseapp.com',
    storageBucket: 'cpmd-final.firebasestorage.app',
  );

}